//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTLocalization.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTLocalization.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Developer&apos;s bitcoin wallet address is copied.
        ///Thanks !! :D과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BitcoinAddressCopiedMsg {
            get {
                return ResourceManager.GetString("BitcoinAddressCopiedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure want to close?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CloseConfirmMsg {
            get {
                return ResourceManager.GetString("CloseConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save your changes?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CloseOrSaveConfirmMsg {
            get {
                return ResourceManager.GetString("CloseOrSaveConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure want to close?
        ///Unsaved changes do not take effect.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CloseWithoutSaveConfirmMsg {
            get {
                return ResourceManager.GetString("CloseWithoutSaveConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download has been cancelled.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DownloadCancelMsg {
            get {
                return ResourceManager.GetString("DownloadCancelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t find &apos;{0}&apos;.
        ///Are you download &apos;{0}&apos;?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DownloadConfirmMsg {
            get {
                return ResourceManager.GetString("DownloadConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;GoodbyeDPI&apos; is already started.
        ///Are you sure want to close?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GoodbyeDPICloseConfirmMsg {
            get {
                return ResourceManager.GetString("GoodbyeDPICloseConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current version is latest.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LatestVersionMsg {
            get {
                return ResourceManager.GetString("LatestVersionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure want to save layout?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LayoutSaveConfirmMsg {
            get {
                return ResourceManager.GetString("LayoutSaveConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find new version.
        ///Are you download ner version?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewVersionDownloadConfirmMsg {
            get {
                return ResourceManager.GetString("NewVersionDownloadConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure want to delete page?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PageDeleteConfirmMsg {
            get {
                return ResourceManager.GetString("PageDeleteConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t remove Main page.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PageDeleteErrorMsg {
            get {
                return ResourceManager.GetString("PageDeleteErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure want to delete item?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PageItemDeleteConfirmMsg {
            get {
                return ResourceManager.GetString("PageItemDeleteConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inputed PageName is already exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PageNameAlreadyErrorMsg {
            get {
                return ResourceManager.GetString("PageNameAlreadyErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must input PageName.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PageNameInputErrorMsg {
            get {
                return ResourceManager.GetString("PageNameInputErrorMsg", resourceCulture);
            }
        }
    }
}
